[package]
name = "contest-app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38",features = ["serde"] }
lapin = "2.5.0"
rand = "0.8.5"
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
